package com.example.minimoneybox.model.session

data class User(
    val AmlAttempts: Int,
    val AmlStatus: String,
    val Animal: String,
    val CanReinstateMandate: Boolean,
    val DateCreated: String,
    val DirectDebitHasBeenSubmitted: Boolean,
    val DirectDebitMandateStatus: String,
    val DoubleRoundUps: Boolean,
    val Email: String,
    val FirstName: String,
    val HasCompletedTutorial: Boolean,
    val HasVerifiedEmail: Boolean,
    val IntercomHmac: String,
    val IntercomHmacAndroid: String,
    val IntercomHmaciOS: String,
    val InvestmentTotal: Int,
    val InvestorProduct: String,
    val IsPinSet: Boolean,
    val JisaRegistrationStatus: String,
    val JisaRoundUpMode: String,
    val LastName: String,
    val LastPayment: Int,
    val MoneyboxAmount: Int,
    val MoneyboxRegistrationStatus: String,
    val MonthlyBoostAmount: Int,
    val MonthlyBoostDay: Int,
    val MonthlyBoostEnabled: Boolean,
    val PreviousMoneyboxAmount: Int,
    val ReferralCode: String,
    val RegistrationStatus: String,
    val RoundUpMode: String,
    val RoundUpWholePounds: Boolean,
    val UserId: String
)